
name: 02-workflow-events     
on: 
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '40 6 * * *' # every day at midnight
    
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: show the trigger
        run: |
         echo "The workflow was triggered by the event: ${{ github.event_name }}"


# jobs:
#   echo-hello:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Say hello
#         run: echo "Hello, world!"

#   echo-goodbye:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Failed step
#         run: |
#           echo "I will succeed!"
#           exit 0
#       - name: Say echo-goodbye
#         run: echo "Goodbye, world!"




# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo to use the action locally
#         uses: actions/checkout@v3.5.3
        
#       - name: Run my own container action
#         id: action
#         uses: ./
#         with:
#           who-to-greet: '@wulfland'
      
#       - name: Output the answer
#         run: echo "The answer is ${{ steps.action.outputs.answer }}"
      
#       - name: Test the container
#         if: ${{ steps.action.outputs.answer != 42 }}
#         run: |
#           echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
#           exit 1









# name: first
# on: push
# jobs:
#   generate-a-secret-output:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Set the value
#       id: step_one
#       run: |
#         echo "action_state=yellow" >> "$GITHUB_ENV"
#     - run: |
#         echo "${{ env.action_state }}" # This will output 'yellow'
    # - id: sets-a-secret
    #   name: Generate, mask, and output a secret
    #   run: |
    #     the_secret=$((RANDOM))
    #     # echo "::add-mask::$the_secret"
    #      echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
    #      echo "$GITHUB_OUTPUT"
    # - name: show the secret
    #   run: |
    #      echo "the_secret is ${{ steps.sets-a-secret.outputs.the_secret }}"
    #      echo "secret-number is ${{ steps.sets-a-secret.outputs.secret-number }}"
     
    # - id: generate
    #   run: |
    #       secret=$((RANDOM))
    #       echo "secret-number=$secret" >> "$GITHUB_OUTPUT"
    # - name: show secret
    #   run: echo "The secret number is ${{ steps.generate.outputs.secret-number }}"

    # - name: Use that secret output (protected by a mask)
    #   run: |
 
# on: 
#   [workflow_dispatch]
# jobs:

#   job_1:
#     strategy:
#       fail-fast: false
#       max-parallel: 3
#       matrix: 
#         os_version: [ubuntu-latest, windows-latest]
#         node_version: [18, 20]

#     name: My first job_1
#     runs-on: ${{ matrix.os_version }}
#     steps:
#       - uses: actions/setup-node@v3.6.0
#         with:
#           node-version: ${{ matrix.node_version }}




  # ubuntu:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run a one-line script
  #       uses: actions/checkout@v4
  #     - name: step two
  #       run: env | sort

  # windows:
  #   runs-on: windows-latest
  #   needs: ubuntu
  #   steps:
  #     - name: Run a one-line script
  #       uses: actions/checkout@v4
  #     - name: step two
  #       run: "get-childitem env: | sort-object Name"
