name: first
on: [workflow_dispatch]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
      - uses: actions/checkout@v4
      - name: step two
        run: env | sort

  windows:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
      - uses: actions/checkout@v4
      - name: step two
        run: "get-childitem env: | sort-object Name"
