name: first
on: push
jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    steps:
    - id: sets-a-secret
      name: Generate, mask, and output a secret
      run: |
        the_secret=$((RANDOM))
        # echo "::add-mask::$the_secret"
         echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
         echo "$GITHUB_OUTPUT"
         echo "the_secret is ${{ steps.sets-a-secret.outputs.the_secret }}"
         echo "secret-number is ${{ steps.sets-a-secret.outputs.secret-number }}"
     
    - id: generate
      run: |
          secret=$((RANDOM))
          echo "secret-number=$secret" >> "$GITHUB_OUTPUT"
          run: echo "The secret number is ${{ steps.generate.outputs.secret-number }}"

    # - name: Use that secret output (protected by a mask)
    #   run: |
 
# on: 
#   [workflow_dispatch]
# jobs:

#   job_1:
#     strategy:
#       fail-fast: false
#       max-parallel: 3
#       matrix: 
#         os_version: [ubuntu-latest, windows-latest]
#         node_version: [18, 20]

#     name: My first job_1
#     runs-on: ${{ matrix.os_version }}
#     steps:
#       - uses: actions/setup-node@v3.6.0
#         with:
#           node-version: ${{ matrix.node_version }}




  # ubuntu:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run a one-line script
  #       uses: actions/checkout@v4
  #     - name: step two
  #       run: env | sort

  # windows:
  #   runs-on: windows-latest
  #   needs: ubuntu
  #   steps:
  #     - name: Run a one-line script
  #       uses: actions/checkout@v4
  #     - name: step two
  #       run: "get-childitem env: | sort-object Name"
